added environmental variable and function variants for different languages (en_US and pt_BR)

diff --git a/install/setup.sh.in b/install/setup.sh.in
--- a/install/setup.sh.in
+++ b/install/setup.sh.in
@@ -19,6 +19,8 @@ export DONNIE_EXEC_PATH="${DONNIE_PATH}/test/stage"
 # is used, this variable should have the robot`s IP address
 export DONNIE_IP=localhost
 export DONNIE_PORT=6665
+# donnie language, default from system
+export DONNIE_LANG="$LANGUAGE"
 
 #required to run donnie
 export PATH=${PATH}:${DONNIE_PATH}/bin
@@ -34,7 +36,7 @@ export LD_LIBRARY_PATH=${DONNIE_PATH}/lib/player:${LD_LIBRARY_PATH}
 # run 'sudo find / -name "*.cmake" -type f' to find all the cmake files for cmake
 VER=$(lsb_release -sr)
 case "${VER}" in 
-	14.04)
+	14.04)	
 		export CMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}:/usr/share/cmake-2.8/Modules/:/usr/share/cmake-2.8/Modules/Platform/:/usr/share/cmake-2.8/Modules/Compiler/:/usr/local/share/cmake/Modules:/usr/local/lib64/cmake/Stage/:/usr/lib/fltk/
 		;;
 	16.04)
@@ -50,6 +52,20 @@ export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig/:/usr/lib/pkgconfig:/usr/lib/x
 alias ssh_donnie='ssh -X pi@${DONNIE_IP}'
 
 function donnie_check_var {
+	if [ -z "$DONNIE_LANG" ]; then
+		echo -e "${RED}ERROR:${NC} Need to set DONNIE_LANG environment variable\n"
+		echo -e "Example: export DONNIE_LANG=pt_BR\n"
+		exit 1
+	fi
+	if [ "$DONNIE_LANG" = "en_US" ]; then
+		donnie_check_var_en
+	fi
+	if [ "$DONNIE_LANG" = "pt_BR" ]; then
+		donnie_check_var_pt
+	fi
+}
+
+function donnie_check_var_en {
 	if [ -z "$DONNIE_PATH" ]; then
 		echo -e "${RED}ERROR:${NC} Need to set DONNIE_PATH environment variable\n"
 		echo -e "Example: export DONNIE_PATH=/opt/donnie\n"
@@ -58,6 +74,19 @@ function donnie_check_var {
 	if [ -z "$DONNIE_SOURCE_PATH" ]; then
 		echo -e "${RED}ERROR:${NC} Need to set DONNIE_SOURCE_PATH environment variable\n"
 		echo -e "Example: export DONNIE_SOURCE_PATH=~/donnie/donnie-assistive-robot-sw\n"
+		exit 1
+	fi  	
+}
+
+function donnie_check_var_pt {
+	if [ -z "$DONNIE_PATH" ]; then
+		echo -e "${RED}ERRO:${NC} É necessário configurar a variável de ambiente DONNIE_PATH\n"
+		echo -e "Examplo: export DONNIE_PATH=/opt/donnie\n"
+		exit 1
+	fi  
+	if [ -z "$DONNIE_SOURCE_PATH" ]; then
+		echo -e "${RED}ERRO:${NC} É necessário configurar a variável de ambiente DONNIE_SOURCE_PATH\n"
+		echo -e "Examplo: export DONNIE_SOURCE_PATH=~/donnie/donnie-assistive-robot-sw\n"
 		exit 1
 	fi  	
 }
@@ -75,7 +104,33 @@ function donnie_login {
 #}
 
 function donnie_desktop_update {
-	donnie_check_var
+	if [ -z "$DONNIE_LANG" ]; then
+		echo -e "${RED}ERROR:${NC} Need to set DONNIE_LANG environment variable\n"
+		echo -e "Example: export DONNIE_LANG=pt_BR\n"
+		exit 1
+	fi
+	if [ "$DONNIE_LANG" = "en_US" ]; then
+		donnie_desktop_update_en
+	fi
+	if [ "$DONNIE_LANG" = "pt_BR" ]; then
+		donnie_desktop_update_pt
+	fi
+}
+
+function donnie_desktop_update_en {
+	donnie_check_var_en
+	echo "Updating donnie in directory ${DONNIE_SOURCE_PATH}"
+    cd "${DONNIE_SOURCE_PATH}/build"
+	git pull origin devel
+	cmake ..
+	make -j 8
+	sudo make install
+	cd -
+	echo "Update complete"
+}
+
+function donnie_desktop_update_pt {
+	donnie_check_var_pt
 	echo "Atualizando o Donnie no diretório ${DONNIE_SOURCE_PATH}"
     cd "${DONNIE_SOURCE_PATH}/build"
 	git pull origin devel
@@ -87,8 +142,46 @@ function donnie_desktop_update {
 }
 
 function donnie_player(){
-  donnie_check_var
-  echo "Executando Donnie software no diretório ${DONNIE_EXEC_PATH}"
+	donnie_check_var
+	if [ "$DONNIE_LANG" = "en_US" ]; then
+		donnie_player_en()
+	fi
+	if [ "$DONNIE_LANG" = "pt_BR" ]; then
+		donnie_player_pt()
+	fi
+}
+
+function donnie_player_en(){
+  echo "Running Donnie software in directory ${DONNIE_EXEC_PATH}"
+  #nohup player ${DONNIE_EXEC_PATH}/server_donnie.cfg &> /dev/null &
+  
+  #Parse options
+  if [ "$1" = "-nogui" ] 
+  then
+    xterm -e "player ${DONNIE_EXEC_PATH}/server_donnie_nogui.cfg &> /dev/null" &
+	sleep 5
+	xterm -e "${DONNIE_PATH}/bin/alerts  &> /dev/null" &
+	sleep 3
+	echo "Running Donnie ..."
+  elif [ "$1" = "--help" ] || [ "$1" = "-h" ] 
+  then
+	echo "Donnie Player launcher"
+	echo "USAGE:  donnie_player [options]"
+	echo -e "\nWhere [options] can be:"
+	echo "  -h, --help         : print this message."
+	echo "  --nogui            : launch player without the graphical interface."
+	#echo "  -c                : acess launch config."
+  else  #default
+	xterm -e "player ${DONNIE_EXEC_PATH}/server_donnie.cfg &> /dev/null" &
+	sleep 5
+	xterm -e "${DONNIE_PATH}/bin/alerts  &> /dev/null" &
+	sleep 3
+	echo "Running Donnie ..."
+  fi
+}
+
+function donnie_player_pt(){
+  echo "Executando software Donnie no diretório ${DONNIE_EXEC_PATH}"
   #nohup player ${DONNIE_EXEC_PATH}/server_donnie.cfg &> /dev/null &
   
   #Parse options
@@ -101,11 +194,11 @@ function donnie_player(){
 	echo "Donnie executando ..."
   elif [ "$1" = "--help" ] || [ "$1" = "-h" ] 
   then
-	echo "Donnie Player launcher"
-	echo "USAGE:  donnie_player [options]"
-	echo -e "\nWhere [options] can be:"
-	echo "  -h, --help         : print this message."
-	echo "  --nogui            : launch player interface without graphic interface."
+	echo "Lançador Donnie Player"
+	echo "USAGEM:  donnie_player [opções]"
+	echo -e "\nOnde [opções] pode ser:"
+	echo "  -h, --help         : imprime esta mensagem."
+	echo "  --nogui            : lança player sem a interface gráfica."
 	#echo "  -c                : acess launch config."
   else  #default
 	xterm -e "player ${DONNIE_EXEC_PATH}/server_donnie.cfg &> /dev/null" &
@@ -117,8 +210,17 @@ function donnie_player(){
 }
 
 function donnie_kill(){
-  killall player
-  echo "Fechando Donnie ..."
+	killall player
+	if [ -z "$DONNIE_LANG" ]; then
+		echo -e "${RED}ERROR:${NC} Need to set DONNIE_LANG environment variable\n"
+		echo -e "Example: export DONNIE_LANG=pt_BR\n"
+	fi
+	if [ "$DONNIE_LANG" = "en_US" ]; then
+		echo "Closing donnie..."
+	fi
+	if [ "$DONNIE_LANG" = "pt_BR" ]; then
+		echo "Fechando donnie..."
+	fi
 }
 
 function donnie_robot_update {
